language: csharp
solution: Wonton.sln
mono: none
dotnet: latest
node_js: "node"

os:
  - linux
  - osx
  - windows

env:
  - CI=false

cache:
  directories:
    - "Wonton.CrossUI.Web/ClientApp/node_modules"

before_install:
  - dotnet tool install --tool-path tools Cake.Tool

install:
  - dotnet restore Wonton.CrossUI.Web/Wonton.CrossUI.Web.csproj

script:
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./tools/dotnet-cake -useMagic="false"          ; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./tools/dotnet-cake -useMagic="false" -targetOS="win"         ; fi
  # - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./tools/dotnet-cake -useMagic="false"          ; fi
  - ./tools/dotnet-cake -useMagic="false"