# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*


jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
  
  - script: dotnet tool install --tool-path tools Cake.Tool
    displayName: 'Install Cake'
  
  - bash: ./tools/dotnet-cake -useMagic="false" -AdditionalName="ubuntu-18.04"
    displayName: 'Build on Linux'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop'
      publishLocation: 'pipeline'
      artifactName: 'Wonton.Linux'

- job: Linux16
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
  
  - script: dotnet tool install --tool-path tools Cake.Tool
    displayName: 'Install Cake'
  
  - bash: ./tools/dotnet-cake -useMagic="false" -AdditionalName="ubuntu-16.04"
    displayName: 'Build on Linux'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop'
      publishLocation: 'pipeline'
      artifactName: 'Wonton.Linux16'

- job: macOS
  pool:
    vmImage: 'macos-10.15'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.101'
  
  - script: dotnet tool install --tool-path tools Cake.Tool
    displayName: 'Install Cake'
  
  - bash: ./tools/dotnet-cake -useMagic="false" -AdditionalName="10.15"
    displayName: 'Build on macOS'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop'
      publishLocation: 'pipeline'
      artifactName: 'Wonton.macOS'

- job: macOS14
  pool:
    vmImage: 'macos-10.14'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.101'

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x' 
      #checkLatest: false # Optional
  
  - script: dotnet tool install --tool-path tools Cake.Tool
    displayName: 'Install Cake'
  
  - bash: ./tools/dotnet-cake -useMagic="false" -AdditionalName="10.14"
    displayName: 'Build on macOS'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop'
      publishLocation: 'pipeline'
      artifactName: 'Wonton.macOS14'

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
  
  - script: dotnet tool install --tool-path tools Cake.Tool
    displayName: 'Install Cake'
  
  - powershell: ./tools/dotnet-cake -useMagic="false"
    displayName: 'Build on Windows'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop'
      publishLocation: 'pipeline'
      artifactName: 'Wonton.Windows'

- job: GithubRelease
  pool: 
    vmImage: 'ubuntu-latest'
  dependsOn:
  - Linux
  - Linux16
  - macOS
  - macOS14
  - Windows
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      itemPattern: '**/*.7z'
      targetPath: '$(System.DefaultWorkingDirectory)/Build'

  - script: dotnet tool install --tool-path tools Cake.Tool
    displayName: 'Install Cake'
  
  - bash: ./tools/dotnet-cake -target="CopyToRelease" -useMagic="false" -releaseDir="$(Build.ArtifactStagingDirectory)"
    displayName: 'Copy Release'

  - script: |
      ls -la $(Build.ArtifactStagingDirectory)
    displayName: 'List artifacts'

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_WangyuHello'
      repositoryName: 'WangyuHello/Wonton'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      releaseNotesSource: 'inline'
      addChangeLog: false
  