# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
  
  - script: dotnet tool install --tool-path tools Cake.Tool
    displayName: 'Install Cake'
  
  - bash: ./tools/dotnet-cake -useMagic="false" -AdditionalName="ubuntu.18.04"
    displayName: 'Build on Linux'

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_WangyuHello'
      repositoryName: 'WangyuHello/Wonton'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      releaseNotesSource: 'inline'
      assets: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop/*.7z'
      addChangeLog: false

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop'
      publishLocation: 'pipeline'
      artifactName: 'Wonton.Linux'

- job: macOS
  pool:
    vmImage: 'macos-10.15'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
  
  - script: dotnet tool install --tool-path tools Cake.Tool
    displayName: 'Install Cake'
  
  - bash: ./tools/dotnet-cake -useMagic="false" -AdditionalName="macOS.10.15"
    displayName: 'Build on macOS'

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_WangyuHello'
      repositoryName: 'WangyuHello/Wonton'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      releaseNotesSource: 'inline'
      assets: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop/*.7z'
      addChangeLog: false

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop'
      publishLocation: 'pipeline'
      artifactName: 'Wonton.macOS'

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
  
  - script: dotnet tool install --tool-path tools Cake.Tool
    displayName: 'Install Cake'
  
  - powershell: ./tools/dotnet-cake -useMagic="false"
    displayName: 'Build on Windows'

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_WangyuHello'
      repositoryName: 'WangyuHello/Wonton'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      releaseNotesSource: 'inline'
      assets: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop/*.7z'
      addChangeLog: false

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/Wonton.CrossUI.Web/bin/Desktop'
      publishLocation: 'pipeline'
      artifactName: 'Wonton.Windows'